<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- 类型定义 -->

    <xs:complexType name="module-config-type">
        <xs:attribute name="url" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="bean-import-type">
        <xs:attribute name="url" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- 元素定义 -->

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module-config" type="module-config-type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="bean-import" type="bean-import-type" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
